// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1lmnCTsp_BsxRIeiDIFxUk9T6s9H3vBk',
    appId: '1:236481371721:web:dea7b57aa271f457dbe998',
    messagingSenderId: '236481371721',
    projectId: 'studentdb-abdd7',
    authDomain: 'studentdb-abdd7.firebaseapp.com',
    storageBucket: 'studentdb-abdd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpunCzU2puXk7im-CHCI_Nkdfp1FIQtoc',
    appId: '1:236481371721:android:52a503af3b8e9576dbe998',
    messagingSenderId: '236481371721',
    projectId: 'studentdb-abdd7',
    storageBucket: 'studentdb-abdd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxzVbsHM9fL3C9_eVc8ekKb1g4lNoLRE',
    appId: '1:236481371721:ios:afcf4648da34315adbe998',
    messagingSenderId: '236481371721',
    projectId: 'studentdb-abdd7',
    storageBucket: 'studentdb-abdd7.firebasestorage.app',
    iosBundleId: 'com.example.travelTourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxxzVbsHM9fL3C9_eVc8ekKb1g4lNoLRE',
    appId: '1:236481371721:ios:afcf4648da34315adbe998',
    messagingSenderId: '236481371721',
    projectId: 'studentdb-abdd7',
    storageBucket: 'studentdb-abdd7.firebasestorage.app',
    iosBundleId: 'com.example.travelTourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoIJ4rRF7bbywvsUtx7hs-kGeTjvC7Jlo',
    appId: '1:236481371721:web:85419fc6ee21ac21dbe998',
    messagingSenderId: '236481371721',
    projectId: 'studentdb-abdd7',
    authDomain: 'studentdb-abdd7.firebaseapp.com',
    storageBucket: 'studentdb-abdd7.firebasestorage.app',
  );
}
